### ISSUE TITLE
Multifactor Authentication

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#152]
https://stormpath.atlassian.net/wiki/display/AM/Multifactor+Authentication AM-3340

**Comment by cilim** [comment]
MFA is implemented, but the travis builds will be failing because the secure keys are currently set to use my tenant on api.stormpath.com which doesn't have MFA enabled (current plan is just a Developer. Needs to be Starter and higher for MFA to work). Also, the base host url is set to use dev.i.stormpath so that the specs pass locally. Don't forget to change it back to the production one :)

Ready for reviewing the PR Damir.

**Comment by cilim** [comment]
Since MFA isn't merged to master yet, we can do Google Authentication in the branch that's currently open and references this issue.

Gonna close this issue and mark as duplicated: https://github.com/stormpath/stormpath-sdk-ruby/issues/186
