### ISSUE TITLE
verify password token fails when periods are encoded

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#154]
I believe SAuthC1 is failing for % in the body.

```ruby
/Users/tom/.rvm/gems/ruby-2.2.2/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/data_store.rb:134:in `execute_request': Authentication required. (Stormpath::Error)
	from /Users/tom/.rvm/gems/ruby-2.2.2/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/data_store.rb:56:in `get_resource'
	from /Users/tom/.rvm/gems/ruby-2.2.2/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/resource/associations.rb:68:in `get'
	from /Users/tom/.rvm/gems/ruby-2.2.2/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/resource/application.rb:101:in `verify_password_reset_token'
	from test.rb:8:in `<main>'
```

test.rb

```ruby
require 'stormpath-sdk'

client = Stormpath::Client.new api_key_file_location: File.join(ENV['HOME'], '.stormpath', 'apiKey.properties')

application_url = 'https://api.stormpath.com/v1/applications/3QIMlJKKN2whGCYzXXw1t8'
application = client.applications.get application_url

account = application.verify_password_reset_token 'eyJ0aWQiOiI3ZzlIRzFZTUJYOG9oRmJ1MEtBRktSIiwic3R0IjoiYXNzZXJ0aW9uIiwiYWxnIjoiSFMyNTYifQ%2EeyJleHAiOjE0NzQ3Mjg5NjUsImp0aSI6IjZka2V4bEMxZm5WZExTNXVYWjBtRzQifQ%2EtEXRF8QVR3_U7QScQSygfRCSEn-9hM4lTnNe7KaSC-E'

puts account.email
```

To reproduce, get a email verification token from an email.

**Comment by cilim** [comment]
@omgitstom you're right. The SAuthC1 algorithm is failing in the ```canonicalize_resource_path``` method where it calls ```encode_url``` and sends the resource_path.

The ```encode_url``` is a method from the ```Utils``` module that is mixed in the ```SauthC1Signer``` and there it escapes the already escaped token.

Looking at the code, the ```encode_url``` receives this value for the path (notice the %2E instead of a period):

```
"/v1/applications/3eE1Jcce080EDxw2q9ChKl/passwordResetTokens/eyJ0aWQiOiI2enlPeVpFRm1tZzRhNmpORlNJOUNYIiwic3R0IjoiYXNzZXJ0aW9uIiwiYWxnIjoiSFMyNTYifQ%2EeyJleHAiOjE0NzUxNDA5MTcsImp0aSI6IjFGanhkWU1zb2o0czhnbHFBNmxWVSJ9%2EE0qBgSl-RQkTvs9RJ43QvKMuZRkvDUStSxfCrIndWLI"
```
and calls ```URI.escape``` on it. Because of that the ```%2E``` become ```%252E``` and therefore the verification of the password token fails.

This issue **only** happens if a user:

1. Resets password in the Stormpath dashboard
2. Copies the password token from the email (instead of just clicking the link to change the password)
3. Pastes the password token and calls:
```ruby
application.verify_password_reset_token(token_from_email)
```

If a user normally generates a password reset token with the Ruby SDK, this problem isn't there, since the Ruby SDK doesn't escape the periods after password token generation. So, this is the right way to do it:

1. Generate password reset token for an account **with** the Ruby SDK: 
```ruby
password_reset_token = application.password_reset_tokens.create(email: account.email).token
```

2. Verify the token:
```ruby
application.verify_password_reset_token password_reset_token
```

What are your thoughts? Should we monkey patch this and check if a path has escaped periods in them and then turn them back to periods or not?

**Comment by cilim** [comment]
Please review @DamirSvrtan
